### ISSUE TITLE
Search bar covers whole header on medium (and above) devices on refresh

### ISSUE THREAD

**Issue by Suhaib-Hilal** [Tauseef-Hilal/FusionFlix#5]
### Issue Description

Search bar covers whole header on medium devices on refreshing the page.

### Expected Behavior

Search bar should not cover whole header section on medium devices

### Actual Behavior

Search bar covers whole header section on medium (and above) devices

### Steps to Reproduce (for Bugs)

Steps are shown in the attached video file

https://github.com/Tauseef-Hilal/FusionFlix/assets/98336906/2c030ac0-4629-497c-9714-2c0c698392d4

**Comment by Tauseef-Hilal** [comment]
Ig I know how to solve this. Thanks for pointing it out
